name: generate config
run-name: ${{ github.actor }} is testing out GitHub Actions ğŸš€
on:
  push:
    branches: [ master ]
  schedule:
    - cron: '0 8,20,23 * * *'
jobs:
  generate-cxxx-conf-job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: python -m pip install requests

      - run: mkdir -p ${{ github.workspace }}/output
      - run: cd ${{ github.workspace }}/output && python ../scripts/run.py
      - run: pwd && ls -lh && git status 
      - name: Push To Pages
        run: |
          git checkout -b dist
          git add -A
          git -c user.name='pat' -c user.email='patvice@live.cn' commit -m 'add dist files'
          remote_addr=`git remote get-url --push origin`
          remote_addr=`echo $remote_addr|  awk -F'://' '{print $2}'`
          remote_addr=https://showmind:${{ secrets.GITHUB_TOKEN }}@${remote_addr}
          git remote add neo ${remote_addr}
          git push neo dist --force



      - run: echo "ğŸ This job's status is ${{ job.status }}."
